### ISSUE TITLE
disable cassandra vm swap

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/cassandra-cf-service-boshrelease#3]
currently managed by helper
waiting correction on bosh https://github.com/cloudfoundry/bosh/issues/1758

**Comment by bgandon** [comment]
The `env.bosh.swap_size` property of `0` is implemented in default BOSH 2.0 manifests.

The cloudfoundry/bosh#1758 issue only shows up when using no ephemeral storage. So, in the general case it does not apply to our context because we attach ephemeral disks to VMs.

**Comment by bgandon** [comment]
Indeed the `env.bosh.swap_size: 0` is not working in our OpenStack context.

We'll add a custom property `no_swap: true` to the `cassandra` job instead.

**Comment by bgandon** [comment]
Done.
Added a custom `disable_linux_swap` property, defaulting to `true`, and an ops file that set this to `false` in Bosh-Lite.
